Goal- Predict customer churn for a bank using its customer's behavior data

In [1]:
import keras #install keras, theano, tensorflow

Using TensorFlow backend.


In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Importing the dataset

dataset = pd.read_csv('C:\Train\Datasets/Churn_Modelling.csv')

In [25]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [27]:
#separating the independent variables and my dependent variable
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [28]:
#Coding our training data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [31]:
X[1:4,]

array([[608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63]], dtype=object)

In [35]:
#Overcoming the shortcomings of LabelEncoding by creating sparse matrix

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
#X = X[:, 1:]

In [36]:
X[1:4,]

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 6.0800000e+02,
        0.0000000e+00, 4.1000000e+01, 1.0000000e+00, 8.3807860e+04,
        1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.0200000e+02,
        0.0000000e+00, 4.2000000e+01, 8.0000000e+00, 1.5966080e+05,
        3.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.9900000e+02,
        0.0000000e+00, 3.9000000e+01, 1.0000000e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 0.0000000e+00, 9.3826630e+04]])

In [37]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [38]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [39]:
from keras.models import Sequential #initialize the neural network
from keras.layers import Dense #adding hidden layers

In [40]:
#Initializing Neural Network
classifier = Sequential()

In [41]:
# Adding the input layer and the first hidden layer
#output_dim= no. of nodes to that layer
#init= initialization of stochastic gradient descent
#input_dim= no. of input parameters, needed only for the first layer

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 12))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
# Adding the output layer, relevance of sigmoid and softmax
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\Gautam\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6, kernel_initializer="uniform")`
  
C:\Users\Gautam\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
C:\Users\Gautam\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


In [42]:
# Compiling Neural Network
#optimizer= adam as the stochastic gradient descent type
#loss= use logarithmic loss function. Since ours is a binary dependent variable, hence- binary_crossentropy
#metrics= model tuning based on accuracy

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [43]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 500)

C:\Users\Gautam\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4853 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4272 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4213 - acc: 0.8037
Epoch 4/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4180 - acc: 0.8254
Epoch 5/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4163 - acc: 0.8279
Epoch 6/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4140 - acc: 0.8285
Epoch 7/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4131 - acc: 0.8306
Epoch 8/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4122 - acc: 0.8310
Epoch 9/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4115 - acc: 0.8311
Epoch 10/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4105 - acc: 0.8317
Epoch 

8000/8000 [==============================] - 1s 93us/step - loss: 0.4017 - acc: 0.8330
Epoch 83/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.4022 - acc: 0.8334
Epoch 84/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4015 - acc: 0.8331
Epoch 85/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4016 - acc: 0.8334
Epoch 86/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4017 - acc: 0.8349
Epoch 87/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4019 - acc: 0.8346
Epoch 88/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4014 - acc: 0.8335
Epoch 89/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4016 - acc: 0.8342
Epoch 90/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4017 - acc: 0.8337
Epoch 91/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4009 - acc: 0.8334
Epoch 92/1

In [51]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.7)

In [52]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[1585,   10],
       [ 342,   63]], dtype=int64)

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.824